### ISSUE TITLE
goblin failed to parse magic number

### ISSUE THREAD

**Issue by Marwes** [m4b/goblin#113]
Seeing this error when running https://github.com/RazrFalcon/cargo-bloat on a project that uses https://github.com/oschwald/maxminddb-rus which seems to generate a .so in addition to the normal static library https://github.com/oschwald/maxminddb-rust/blob/ff8ff2106a867f05d3526b2e9d0f729082ce5745/Cargo.toml#L17.

Just guessing that the .so contains something goblin can't handle (yet) but it might also be cargo-bloat that uses it wrong.

```
Error: 'goblin' failed to parse '"<SNIP>/target/debug/deps/libmaxminddb-00b74459be63a99f.so"' cause 'Invalid magic number: 0x10102464c457f'.
```

**Comment by philipc** [comment]
It's an error in cargo-bloat. It's trying to treat the .so as an archive.

**Comment by Marwes** [comment]
Aha, seems I guess wrong then. Sorry for the bother. Opened an issue in cargo-bloat instead!
