### ISSUE TITLE
Section relocations are not parsed even if they exist

### ISSUE THREAD

**Issue by Techno-coder** [m4b/goblin#117]
Linkers can be forced to generate relocations even if the format is not designed to have section relocations (such as the `--emit-relocs` flag for `ld.lld`). Goblin only parses the section relocations if the file type is `ET_REL` which means the `shdr_relocs` field is empty. I think it would be better to parse section relocations if they exist rather than relying on the file type. 

For example, I'm generating a position independent executable with `--pie` (with a file type of `ET_DYN`) and I want to relink the executable once it's located in memory but this is only possible with access to the parsed relocations.

**Comment by m4b** [comment]
@techno-coder thanks for the issue and yes, that sounds reasonable!

I can’t remember why it was this way; might have been a premature optimization, might have been for what seemed like a good reason before, or perhaps not at all? Not sure.

I don’t think it would be hard to add, but need to make sure it doesn’t break stuff. I increasingly wish we had more unit tests or a “parser run” with expected values, etc., of each. Anyway seems reasonable, and I don’t think the PR would be too bad.

@philipc does this seem reasonable to you ?

**Comment by philipc** [comment]
Sounds like a correct and relatively safe change to me.

**Comment by Techno-coder** [comment]
No code within goblin accesses the `shdr_relocs` field other than the construction of it: [Github search query](https://github.com/m4b/goblin/search?q=shdr_relocs&unscoped_q=shdr_relocs), so surely this code change would not be able to affect any of goblin's parsed data structures other than that particular field?

Hardly any public repositories on Github uses the `shdr_relocs` field: [Github search query](https://github.com/search?p=2&q=shdr_relocs&type=Code). Out of the four that actually accesses the field, two of them are designed to reprocess the sections data into a different format: [m4b/bingrep](https://github.com/m4b/bingrep/blob/2d9925eb65b3e59cf9ab53397c40fa190195b1d0/src/format_elf.rs) and [gimli-rs/object](https://github.com/gimli-rs/object/blob/27474abea68f99a6898f3fd66213eeabc0a3dd3f/src/elf.rs). One is a ROM compiler for the Gamecube that uses a relocatable ELF file (`ET_REL` which will not be affected): [CryZe/romhack-compiler](https://github.com/CryZe/romhack-compiler/blob/fe09c079c4325704bf05b651c2dd18bc7aded3ca/backend/src/linker.rs), and the last one (at a cursory look) seems to rewrite the relocation data into its own executable format: [redsift/redbpf](https://github.com/redsift/redbpf/blob/95d7bae91f7699d4f1577e201f2b5fe918bc0218/src/lib.rs).

**Comment by m4b** [comment]
To be clear the public fields type hasn’t changed (ie it’s a backwards compatible fix, yes)?
Also wow thanks for doing the manual reverse deps lookups, that’s quite nice of you!
