### ISSUE TITLE
VS_VERSION_INFO

### ISSUE THREAD

**Issue by theflakes** [m4b/goblin#123]
I apologize if I'm blind and not finding this. But, are VS_VERSION_INFO fields accessible in Goblin?

thanks

**Comment by m4b** [comment]
Hello, could you elaborate ? I’ve never heard of it so probably not ? Is this a PE binary thing or something else ?

**Comment by theflakes** [comment]
Sorry, should have explained better. VS_VERSION_INFO is for PEs. Its useful for forensic analysis if fields are populated and why I'm interested in it.

https://www.conedogers.com/2012/08/06/retrieving-windows-vs_versioninfo-struct-from-a-binary/
https://stackoverflow.com/questions/14184207/is-vs-version-info-a-resourcedirectory-resourceentry-and-does-it-have-a-name-or

**Comment by willglynn** [comment]
`VS_VERSION_INFO` is stored as a resource, which is a type of auxiliary data PEs can contain. (Icons are the other common use of resources, though there are more.) `goblin` can provide the RVA of the resource table via `goblin::pe::PE` -> `header` -> `optional_headers` -> `data_directories` -> `get_resource_table()`, but it doesn't currently parse the resource table itself or any `VS_VERSION_INFO` struct which might be inside.

**Comment by theflakes** [comment]
Cool, thanks for the insight. I'll see what I can do with that when I get some time.

**Comment by m4b** [comment]
Is this still an issue or can I close ?

**Comment by theflakes** [comment]
I've not had any time to look at it, no worries about closing it and thanks.

**Comment by m4b** [comment]
Ok let me know if you have any questions or want to contribute in any way :) I think @willglynn knows better and could provide a good solution for what to do in case you want this information.
