### ISSUE TITLE
Increase rustc supported version?

### ISSUE THREAD

**Issue by lzutao** [m4b/goblin#130]
Ubuntu OS already supports at least [rustc 1.30](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=rustc&searchon=names).
Increase rustc supported version help cleaning up deprecated codes.

**Comment by lzutao** [comment]
I see this #104. So It would be the same thing to me.

**Comment by m4b** [comment]
Yes if we bump minimum I think we should go for minimum rust 2018 edition compiler ? Or a semi recent one that one would find on Ubuntu, fedora, etc. can’t remember what rustc fedora ships at the moment

**Comment by lzutao** [comment]
Closed in favor of #104.
