### ISSUE TITLE
casting from `*const u32` to a more-strictly-aligned pointer (`*const u64`)

### ISSUE THREAD

**Issue by lzutao** [m4b/goblin#149]
This is the last error from clippy:
```rust
error: casting from `*const u32` to a more-strictly-aligned pointer (`*const u64`)
   --> src/elf/gnu_hash.rs:60:38
    |
60  |                 let bloomwords_ptr = hashtab.add(4) as *const $size;
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | 
   ::: src/lib.rs:365:9
    |
365 |         elf_gnu_hash_impl!(u64);
    |         ------------------------ in this macro invocation
    |
    = note: #[deny(clippy::cast_ptr_alignment)] on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cast_ptr_alignment

error: aborting due to previous error
```

I don't know enough about implementation details of GNU Hash to know that this cast is safe or not. So I leave it to you (@m4b , @philipc ).

There are two things we could do:
- If this is safe to cast, we ignore the error with clippy attribute.
- If this is unsafe, how do we fix or recover from this cast?

**Comment by lzutao** [comment]
Ping @philipc : Do you have any ideas to about this?

**Comment by philipc** [comment]
It's only safe if the provided `hashtab` pointer has the correct alignment. This will be up to the caller to ensure by loading the .gnu_hash section into memory with the correct alignment. I guess we could make this explicit by changing the function signature to require `hashtab: *const $size`. That still makes it hard to write the function internals in a way that avoids the clippy warning though.
