### ISSUE TITLE
Nightly doc for goblin

### ISSUE THREAD

**Issue by lzutao** [m4b/goblin#156]
cc @m4b @philipc 
I think about deploying nightly doc (whenever commits pushed to master branch)
of goblin to github pages. The reason is that we could see which changes happened
visually after applying a documentation improvement PR.

**Comment by m4b** [comment]
Yes I like this idea :) how hard would it be to setup ?

**Comment by lzutao** [comment]
Easily. I'll send a PR for this.

**Comment by m4b** [comment]
Dumb question: how do we see the docs now? :D

**Comment by m4b** [comment]
Nevermind, figured it out; they're right here: http://www.m4b.io/goblin/goblin/index.html

great work @lzutao !
