### ISSUE TITLE
reexport lib name may be truncated

### ISSUE THREAD

**Issue by williballenthin** [m4b/goblin#160]
Reviewing the exports of `kernel32.dll`, it looks like the `lib` field of reexports may be truncated by one character:

![image](https://user-images.githubusercontent.com/156560/57873432-77979500-77cb-11e9-91dd-cc98a63c5cef.png)

I believe the expected value should be `NTDLL`:

![image](https://user-images.githubusercontent.com/156560/57873465-91d17300-77cb-11e9-9a13-1d1cbd2fcfdd.png)

**Comment by m4b** [comment]
What does the library name say ? I recall in the past thinking it was wrong but it actually matches the real dll name other libs use to link against

**Comment by philipc** [comment]
@m4b Look at the second image, the actual string is "NTDLL.RtlAcquireSRWLockExclusive". All that the parsing code should be doing is splitting at the ".", it shouldn't be dropping the last letter of "NTDLL" too. So looks like a clear bug to me.

**Comment by m4b** [comment]
Where is the string coming from ? Is it from another program ? I distinctly remember a library name which I thought was incorrect in an msvc library before but I could be misremembering.

Regardless, I still haven’t gotten answer to my original question: what is the dll name?

**Comment by williballenthin** [comment]
> I believe the expected value should be `NTDLL`

**Comment by m4b** [comment]
Sorry I’m not in front of s computer. Otherwise I’d try to check myself. Please show the full debug output of goblin on the binary; it should list which dlls it links against/requires. That’s the name I’m asking for.

**Comment by m4b** [comment]
If we are dropping a character I’m sure it’s a regression and we should git bisect ?

**Comment by williballenthin** [comment]
here is the log output from goblin at level `Debug`. let me know if you need `Trace`. [goblin.log](https://github.com/m4b/goblin/files/3189963/goblin.log)

**Comment by m4b** [comment]
Yup this is definitely fucked :(
```
       Export {
            name: Some(
--
            rva: 920705,
            size: 0,
            reexport: Some(
                DLLName {
                    export: "RtlWakeConditionVariable",
                    lib: "NTDL"
                }
            )
        },
        Export {
            name: Some(
--
            rva: 938124,
            size: 4
        },
        Import {
            name: "RtlDoesFileExists_U",
            dll: "ntdll.dll",
            ordinal: 832,
            offset: 925720,
            rva: 938144,
            size: 4
        },
        "api-ms-win-core-windowserrorreporting-l1-1-0.dll",
        "api-ms-win-core-wow64-l1-1-0.dll",
        "api-ms-win-core-xstate-l2-1-0.dll",
        "api-ms-win-security-appcontainer-l1-1-0.dll",
        "api-ms-win-security-base-l1-2-0.dll",
        "ntdll.dll"
    ],
```
I'm surprised it took this long to get this bug report :(

**Comment by m4b** [comment]
Yea this is probably my least favorite code in goblin: https://github.com//m4b/goblin/blob/779d0ce835bb325327f39157ea8fdb8882daa171/src/pe/export.rs#L159

and i'm to blame cause I wrote it fast and under duress :sweat_smile:

**Comment by m4b** [comment]
I can't bisect this; at least not far enough, at some point goblin was using git scroll in toml, and it breaks the build sadly. Regardless I think I'm wrong and it's always been broken :scream_cat: I thought it might have been introduced in the rustfmt refactor, which I explicitly noted in review i didn't really know what was going on, but yea, i think its just always not worked.
