### ISSUE TITLE
how to interpret `pe::import::Import` fields?

### ISSUE THREAD

**Issue by williballenthin** [m4b/goblin#161]
Would you please describe the meaning of the fields exposed by `pe::import::Import`?

  - `dll`: name of imported DLL
  - `name`: name of imported function (or empty if import by ordinal only?)
  - `ordinal`: ordinal of imported function
  - `offset`: I don't know. file offset to something?
  - `rva`: I don't know. RVA of something?
  - `size`: I don't know.

What I would like to do is map the symbol name (e.g. `{dll}!{name}`) to the RVA of the First Thunk entry of the imported function. That is, when I see a reference to a First Thunk entry, I know which symbol it would refer to.

However, I understand there are a number of structures that support imports in PE files. Maybe the above fields point to a different part of these structures. So, I'd like to confirm if goblin does support the above, if it can/should be extended, or I should do this parsing myself. Hence, the above question, since the documentation is not yet very clear on the topic.

**Comment by m4b** [comment]
@willglynn if you have some cycles perhaps you could field this question ?

**Comment by williballenthin** [comment]
based on inspection of some sample .dll files using a hex editor, I gather that:

  - `rva` is the RVA of the name of the symbol, e.g. `RtlAcquireSRWLockExclusive`
  - `addr` is the RVA of the pointer to the RVA of the name (`rva` above)

Is there an exposed way to get the thunk entry of the imported function?

**Comment by williballenthin** [comment]
i've ended up implementing the import table parsing myself.
