### ISSUE TITLE
Remove cow from `Strtab`

### ISSUE THREAD

**Issue by m4b** [m4b/goblin#17]
This will force `Strtab` to be zero-copy and also usable in `no_std` scenarios (which someone complained about wasn't possible).

This is easy, just deletion of code, and update definitions.  But this is blocked on #14, #15, #16

Will close #12 , as it makes it no longer necessary.

**Comment by morrme** [comment]
I can pitch in to do the deletions/updates with a little guidance. I've located the file and see the references.

**Comment by m4b** [comment]
@morrme awesome ! I think I can finish the elf changes fairly quickly, which is the primary blocker.

So primary changes are:

1. Deletion of the cow usage and import, update methods respectively. 
1. Removal of std compilation flags on strtab module . This is hard to test currently. I usually run `make api` and verify everything compiles without warnings. Really need a dummy project which uses elf in no std context. 
2. Removal of the duplicate logic in `get_str` can simply be replaced with `bytes.pread::<&str>`
3. While we're at it, add some tests for \n delimited tables, etc. 

There's probably some other things but that's the general gist!

**Comment by m4b** [comment]
FYI this will have annoying lifetime issues and will likely require annotations in various parts of clients, and likely explicit annotations in the impl of the strtab itself. But it should be possible.

**Comment by m4b** [comment]
PSS @morrme actually I think these changes need to be made in tandem with elf zero copy #15, as a full version will be blocked on this iirc. I will push a minimal change to elf parser tonight which will allow you to make these changes, and then should be able to work on this as soon as you want.

**Comment by m4b** [comment]
@morrme K don't worry about tests, current ones should cover it.

I think you can start on this now (need to pull latest master though); the various clients, archive, and elf should now be passing a lifetime parameter to their instances like so: `Strtab<'a>` (instead of previous `'static`)

which means should be ready to be de-cow-ified, etc.

Let me know if you have any problems or questions :) and have fun!

**Comment by m4b** [comment]
@morrme you still working on this ? It's ok if you're too busy :) just wondering if I should start on it or not

**Comment by morrme** [comment]
@m4b i actually got stuck.  if you've freed up, you can probably get it done quickly. i will check it out afterwards to see what i missed! :)

**Comment by m4b** [comment]
This is very likely my fault :/ I'm in the process of reverting `AsRef<[u8]>` everywhere due to the mechanics of it forcing local borrows. This isn't a problem until you try to embed the parse function in another function in which case the borrow is local and it won't last long enough ... this might be catching you up and I'm sorry about that if so. 

Once this painful transition is over converting the internals of elf and pe to zero copy strings, etc will be easy and perhaps something you'd be interested in ? In particular making the interpreter a borrowed str along with some other fixes should be relatively straightforward, I can let you know when it's ready. 

And really appreciate you looking into it and expressing interest in helping in the first place :)
