### ISSUE TITLE
Parsing of static Windows library archives fails

### ISSUE THREAD

**Issue by raindev** [m4b/goblin#173]
I've got some Windows static libraries (`.lib` archives) that goblin fails to parse. One file is a toy example consisting of two "hello world" object files[1], another one is BoringSSL crypto module[2]. Both are built on Windows 10 using Visual Studio toolchain[3]. The error is `type is too big (4) for 3`.

Debugging revealed that the problem is caused by invalid symbol lookup table size read here: https://github.com/m4b/goblin/blob/master/src/archive/mod.rs#L200
Because the size is too large, the loop goes on reading 4-byte values until reaching the end of the buffer, failing if buffer size is not divisible by 4.

Taking `lib.lib` as an example there're two symbol lookup tables (member name is `/`, space padded to the right). Both members are 151 bytes large (hence 3 bytes unparsable into u32 left). One of them (offset 0x44) has correct table size: `00 00 00 06` (big endian) is parsed correctly, the other (offset 0x118) however starts from of `02 00 00 00` (way out of range for string table size). It turned out Windows extends System V archive format adding a second symbol lookup table (they call it Linker Member) named `/` which has a different format[4]. E.g. the first 4 bytes is the number of archive members little-endian, not the size of string table big-endian.

Since a second file named `/` could only be present in Windows library archives, it should be easy to implement support for without breaking System V compatibility. I hope to follow up with an implementation.

This might be the same problem from #133 but I'm yet to confirm it.

1. https://www.dropbox.com/s/df7su6n9r26472i/lib.lib?dl=0
2. https://www.dropbox.com/s/9zy9sa7k5bmf9cp/crypto.lib?dl=0
3. Microsoft C/C++ Optimizing Compiler Version 19.21.27702.2 for x64, Incremental Linker Version 14.21.27702
4. https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#second-linker-member

**Comment by m4b** [comment]
Wow, thanks for the great write up ! Very interesting stuff :)

If you’ve got an idea for an implementation and some time, go for it! Looking forward to it :)
