### ISSUE TITLE
PE parse fail with invalid exception directory table size

### ISSUE THREAD

**Issue by wyxloading** [m4b/goblin#179]
`bad input invalid exception directory table size (17920)`

I get this error while reading a dll downloaded from microsoft symbol server. `advapi32.dll` (attach below).
There are more dlls report the same error (with different table size).
I don't know it should consider as a bug or something. Does anyone know about this?

[advapi32.zip](https://github.com/m4b/goblin/files/3490604/advapi32.zip)

**Comment by philipc** [comment]
It's a bug. It looks like this is a 32-bit file, whereas the `ExceptionData` handling can only handle x84-64 exception handling. I couldn't find any documentation on what the .pdata section contains for 32-bit, so I suggest fixing goblin so that it ignores .pdata if the machine isn't x86-64. This is what llvm-objdump does.

**Comment by wyxloading** [comment]
Does this document help?

https://docs.microsoft.com/zh-cn/windows/win32/debug/pe-format#the-pdata-section

**Comment by philipc** [comment]
I can't see anything about 32-bit x86 there. From inspecting the data, it looks like each entry is 8 bytes.

**Comment by wyxloading** [comment]
Thanks @philipc. According to llvm coffdump, looks like .pdata section size do not need to be multiple of 12 (sizeof `RuntimeFunction`). 
Should i fix this issue like llvm does?

https://github.com/llvm-mirror/llvm/blob/709ddb3442d536da89edd05c66133466a6509bb9/tools/llvm-objdump/COFFDump.cpp#L439-L467
https://github.com/llvm-mirror/llvm/blob/709ddb3442d536da89edd05c66133466a6509bb9/lib/Object/COFFObjectFile.cpp#L1121-L1136

**Comment by philipc** [comment]
Yes fix it like llvm does. But to be be clear, llvm only tries to parse this section for AMD64, and we should do the same for now:
https://github.com/llvm-mirror/llvm/blob/709ddb3442d536da89edd05c66133466a6509bb9/tools/llvm-objdump/COFFDump.cpp#L591-L596
So no need to change the size check in goblin.

**Comment by philipc** [comment]
Fixed in #180

**Comment by m4b** [comment]
Thank you @wyxloading!
