### ISSUE TITLE
pe::CoffHeader::sections produces duplicated sections?

### ISSUE THREAD

**Issue by RazrFalcon** [m4b/goblin#187]
I was looking through the sources and noticed that `pe::CoffHeader::sections` creates `nsections` with the same data:

https://github.com/m4b/goblin/blob/189216544ca63e97d9737120a37605c0fa4bfe56/src/pe/header.rs#L66-L76

This line always receives the same data, unless I'm mistaking. 

https://github.com/m4b/goblin/blob/189216544ca63e97d9737120a37605c0fa4bfe56/src/pe/header.rs#L72

**Comment by m4b** [comment]
Offset is a mutable reference. The section parser updates that offset when it parses a section out, which is why it parses different sections.

Yes it’s a little unclear unless you see the mutable reference :)

**Comment by RazrFalcon** [comment]
I see, my bad.
