### ISSUE TITLE
Some problems with parsing core dumps

### ISSUE THREAD

**Issue by xcoldhandsx** [m4b/goblin#199]
Hello!
I decided to continue my experiments with parsing core dumps. And the first thing I've done: I updated the goblin. Unfortunately, the current version returns a error, when i tried to parse some core dumps: **parse object: Scroll(TooBig { size: 1905784752, len: 258048 })**.  I was debugging a little  trying to locate a problem.
![Screenshot at 2019-12-22 16:57:59](https://user-images.githubusercontent.com/38811376/71323957-2cc0c700-24ea-11ea-8c46-a8e8386ded37.png)
Here, we've got bad sizes and received an error. Maybe problem is that there is no sections in core file?
Here  is the output of readelf tool:
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              CORE (Core file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          0 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         18
  Size of section headers:           0 (bytes)
  Number of section headers:         0
  Section header string table index: 0

There are no sections in this file.

There are no sections to group in this file.

Readelf and old version of goblin could parse my core file. Any ideas?

**Comment by xcoldhandsx** [comment]
As I discovered, the problem is because of  **There are no sections in this file**. Here in 
https://github.com/m4b/goblin/blob/master/src/elf/section_header.rs:438  strange things are happening.

```rust
 pub fn parse(bytes: &[u8], mut offset: usize, count: usize, ctx: Ctx) -> error::Result<Vec<SectionHeader>> {
            use scroll::Pread;
            let mut section_headers = Vec::with_capacity(count);
            let mut nsection_headers = count;
            let empty_sh = bytes.gread_with::<SectionHeader>(&mut offset, ctx)?;
            if count == 0 as usize {
                nsection_headers = empty_sh.sh_size as usize;
            }
            section_headers.push(empty_sh);
            for _ in 1..nsection_headers {
                let shdr = bytes.gread_with(&mut offset, ctx)?;
                section_headers.push(shdr);
            }
            Ok(section_headers)
        }
```
In my case **offset** and **count** are equal to zero. Why do we need  this code?
```rust
 if count == 0 as usize {
                nsection_headers = empty_sh.sh_size as usize;
 }
```
Maybe if **count** is equal to zero we want return an empty vector? Also, I think some checks for offset is needed too.

**Comment by m4b** [comment]
Darn looks like a regression :( can you paste the core file somewhere ?

**Comment by xcoldhandsx** [comment]
Sure, here it is inside zip archive.
[core-bug.zip](https://github.com/m4b/goblin/files/3992915/core-bug.zip)

**Comment by philipc** [comment]
Definitely need checks for `offset != 0` before reading `empty_sh`. That `empty_sh` stuff is to handle large numbers of sections that overflow the `u16` field, in which case the number of sections is stored in the first section header. But if `offset == 0` then there isn't even a first section header.
