### ISSUE TITLE
goblin::mach::load_command::Segment::sections() returns sections with wrong lifetime

### ISSUE THREAD

**Issue by philipc** [m4b/goblin#22]
I'm trying to use goblin as the object file loader in the gimli crate. Basically all it needs to do is parse the ELF/Mach-O header and return the data for sections with a given name.

However, I'm having trouble getting Mach-O sections, because `Segment::sections()` returns sections that have the lifetime of the segment, instead of the data. That is, `Segment::sections()` is defined as:
````
impl<'a> Segment<'a>
    pub fn sections<'b>(&'b self) -> error::Result<Vec<Section<'b>>> {
        ...
    }
}
````

but I want:
````
impl<'a> Segment<'a>
    pub fn sections<'b>(&'b self) -> error::Result<Vec<Section<'a>>> {
        ...
    }
}
````

Fixing this will probably require changing the `scroll::Gread` trait, but I'm having too much trouble understanding how that works to be able to fix it myself.

For reference, here's how I'm trying to call it:
````
fn macho_get_section<'a>(macho: &mach::MachO<'a>, section_name: &str) -> Option<&'a [u8]> {
    let segment_name = "__DWARF";
    let section_name = macho_translate_section_name(section_name);

    for segment in &*macho.segments {
        if let Ok(name) = segment.name() {
            if name == segment_name {
                if let Ok(sections) = segment.sections() {
                    for section in sections {
                        if section_name == parse_section_name(&section.sectname[..]) {
                            return Some(section.data);
                        }
                    }
                }
            }
        }
    }
    None
}
````

**Comment by m4b** [comment]
@philipc Hi and thanks for the issue !

So this makes me sad, you are correct; something is broken with `gread_with` lifetimes :/

However, I've patched and fixed it using just the `pread_with` alternative and manual offset incrementing.

I've also added a new test that should ferret out any regressions in lifetime issues like this, basically copying above code: https://github.com//m4b/goblin/blob/56c8baa7e959a87b9087620bbc9a97b548c48fa3/tests/macho.rs#L29.

I also added a `name()` to `Section` as it seemed like you were using it.

In the meantime, hopefully I can fix `gread`.  If you could temporarily test on master and see whether this fixes the issue for me, let me know, and I'll start on publishing a new crates.io version for you to use.

Thanks for the issue and the detailed report :)

**Comment by philipc** [comment]
Thanks for the quick fix; that fixes compilation for me. I haven't actually tested that it executes properly yet though, because I don't have access to any Mach-O binaries with DWARF debug info to test with. I hope to resolve that soon.

**Comment by philipc** [comment]
I managed to get a binary out of travis, and that all works fine, including the new `Section::name()` method. A new crates.io version would be great, thanks.

**Comment by m4b** [comment]
FTR, the fix in scroll was just a mistakenly forgotten `[u8]` impl :/

e.g.:

```rust
impl<Ctx, E> Gread<Ctx, E> for [u8] where
    [u8]: TryOffsetWith<Ctx, E>,
    Ctx: Copy + Default + Debug,
    E: Debug {}
```

I'm glad this was caught though, and again thanks for the report!  I'll work on getting a new version of goblin out asap, maybe tonight
