### ISSUE TITLE
missing arch names on OSX

### ISSUE THREAD

**Issue by blinsay** [m4b/goblin#231]
I've been playing around with Goblin on OSX and noticed that the arch names for my multi-arch binaries aren't being output correctly. `file` seems to get it correct, so I don't think there's anything strange going on with my system.

Thanks for a cool project, let me know if I can provide anything else that's helpful.

```
 $ file /usr/bin/ruby
/usr/bin/ruby: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [i386:Mach-O executable i386]
/usr/bin/ruby (for architecture x86_64):        Mach-O 64-bit executable x86_64
/usr/bin/ruby (for architecture i386):  Mach-O executable i386
$ cargo run -q /usr/bin/ruby
/usr/bin/ruby
- unknown (cputype=0x01000007, cpusubtype=0x80000003)
- i386 (cputype=0x00000007, cpusubtype=0x00000003)
```

```rust
use goblin::mach::constants::cputype::get_arch_name_from_types;
use goblin::mach::Mach;
use std::env::args;
use std::fs::read;

fn main() {
    for path in args().skip(1) {
        println!("{}", path);
        let buf = read(path).unwrap();

        if let Ok(Mach::Fat(m)) = Mach::parse(&buf) {
            for i in 0..m.narches {
                let a = m.get(i).unwrap();
                let cputype = get_arch_name_from_types(a.header.cputype, a.header.cpusubtype)
                    .unwrap_or("unknown");
                println!(
                    "- {} (cputype=0x{:08x}, cpusubtype=0x{:08x})",
                    cputype, a.header.cputype, a.header.cpusubtype
                );
            }
        }
    }
}
```

**Comment by blinsay** [comment]
Expanded the repro a bit to scan for binaries where the arch name is `None` and it seems like it's always the `cputype=0x01000007 cpusubtype=0x80000003` pair.

**Comment by Evian-Zhang** [comment]
When using `get_arch_name_from_types` for Mach-O files, we should use `a.header.cputype()` and `a.header.cpusubtype()` instead of `a.header.cputype` and `a.header.cpusubtype`. This may help you solve this problem. I would like to open a PR to add more documentation for this method and add some explanation.

**Comment by m4b** [comment]
@blinsay I believe @Evian-Zhang comment + documentation changes answers your issue? If yes, would you mind closing? And thanks again for opening the issue!

**Comment by blinsay** [comment]
Using the method worked, thanks for clarifying!

fwiw - to fix my repro I ended up calling `a.cputype()` since `FatArch` doesn't have a `header`. Might be worth putting a note on the struct fields in addition to the method.
