### ISSUE TITLE
Incorrect file_range for ELF sections with type SHT_NOBITS

### ISSUE THREAD

**Issue by Tiwalun** [m4b/goblin#252]
I've noticed that goblin returns a non-empty range when `file_range()` is called on a section header with type `SHT_NOBITS`.

From what I understand, these sections don't have any data in the file itself, and only exist in memory. I would expect that the returned range is empty in that case. The returned file range also overlaps with the file range of the next section.

I would suggest that the `file_range` function should check the type, and return an empty range in case its NOBITS. If that's ok I can do a PR.

**Comment by m4b** [comment]
Yes that sounds right to me, if you made a PR that would be great :)
