### ISSUE TITLE
Replace `pub type` with `pub use`

### ISSUE THREAD

**Issue by sollyucko** [m4b/goblin#257]
# Current state
`elf/mod.rs` (and possibly other modules; I haven't checked), have a bunch of "trivial" `pub type` type aliases that could be replaced with `pub use`: https://github.com/m4b/goblin/blob/master/src/elf/mod.rs#L72-L80.

# The problem
```
error[E0659]: `SectionHeader` is ambiguous (glob import vs glob import in the same module)
  --> src\lib.rs:61:29
   |
61 |     SecRel { section: &'elf SectionHeader, offset: u64 },
   |                             ^^^^^^^^^^^^^ ambiguous name
   |
note: `SectionHeader` could refer to the type alias imported here
  --> src\lib.rs:23:9
   |
23 |         *, // Elf
   |         ^
   = help: consider adding an explicit import of `SectionHeader` to disambiguate
note: `SectionHeader` could also refer to the struct imported here
  --> src\lib.rs:25:9
   |
25 |         section_header::*, // SHN_*
   |         ^^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `SectionHeader` to disambiguate
```

# History, according to Git

Originally, all of the `pub type`s were non-trivial, targeting `Unified`s, but then they were gradually changed such that they became their own types.

- https://github.com/m4b/goblin/commit/244fdf9f73372a8b190fc6324fec41cd49b9400d#diff-696bbf0d8b3f75177e0fa931a45c3e85057e2078598ee1cf8040393730b30633R217-R222: a bunch of non-trivial type aliases are introduced privately.
- https://github.com/m4b/goblin/commit/62d9b59dc932c53dfbeafa6f4fbb9ea74fce06c0: `type Header` is made `pub`
- https://github.com/m4b/goblin/commit/d0d5e00f6046a9563d47269b106bd2b8b8104ab0: the rest of them are made `pub`
- https://github.com/m4b/goblin/commit/a6df163932de7506559e1dcde3ccf920e2250ebe#diff-696bbf0d8b3f75177e0fa931a45c3e85057e2078598ee1cf8040393730b30633R228: `Header` is made trivial.
- https://github.com/m4b/goblin/commit/e295bf6f957ea6806c8b717f282db55ba9f0b084#diff-696bbf0d8b3f75177e0fa931a45c3e85057e2078598ee1cf8040393730b30633R230: `SectionHeader` is made trivial.
- https://github.com/m4b/goblin/commit/8f91548ee2b75bec6f51c260238ed305712d3083#diff-696bbf0d8b3f75177e0fa931a45c3e85057e2078598ee1cf8040393730b30633R233: `ProgramHeader` is made trivial.
- https://github.com/m4b/goblin/commit/adfd5d2118aac9b5f379d600f6eeb48bad82a35c#diff-696bbf0d8b3f75177e0fa931a45c3e85057e2078598ee1cf8040393730b30633R235: `Sym` is made trivial.
- https://github.com/m4b/goblin/commit/29b75b660360c9cec29f3b3ee3d029eebd960f6a#diff-696bbf0d8b3f75177e0fa931a45c3e85057e2078598ee1cf8040393730b30633R235-R236: `Dyn` and `Dynamic` are made trivial.
- https://github.com/m4b/goblin/commit/be06906543dc0bbf76228c16e82dc4dd1d6523a0#diff-696bbf0d8b3f75177e0fa931a45c3e85057e2078598ee1cf8040393730b30633R87: `Reloc` is introduced as a trivial `pub type`.

# My proposal

To the extent possible, i.e. when the target of the `pub type` is a single path, especially where the name is the same (this excludes cases such as `pub type ShdrIdx = usize`), `pub type`s should be converted into `pub use`s.

# Advantages

AFAIK, this should prevent a `use` of the original and the alias from conflicting.

# Disadvantages

Are there any potential backwards-compatibility issues, or any other issues with this change?

# Conclusion

If this sounds like something you'd want or at least be okay with, let me know and I'd be happy to submit a PR.

**Comment by m4b** [comment]
Wow thanks for the very nice issue write up !

I can’t quite remember the rationale (if any) for using pub type. It’s possible there were some issues before the great module change that I was trying to work around? Or maybe not, it was some time ago !

Your proposal tentatively seems good.

I’m unsure about the semver requirements for pub type and pub use ? It’s probably fine since they’re in same module.

I assume (but am not sure) the compile time won’t be affected either, but that should be easy to check I believe.

If you like and have time we can try out a PR and see if anything weird happens :) also a test showing the import can be done without error as you have above would also be good

**Comment by sollyucko** [comment]
I have submitted #259. FWIW, AFAICT the reason for having `pub type` earlier is that `pub use` only works if the target is a path as opposed to an instantiation of generics (e.g. `Unified<...>`).
