### ISSUE TITLE
elf: Implement parsing of symbol versioning

### ISSUE THREAD

**Issue by messense** [m4b/goblin#263]
See https://github.com/PyO3/maturin/pull/436/files#r581158722

**Comment by johannst** [comment]
Hey :]
I'd be interested to take a look at this issue. If that's fine you can just assign me.
I planned to prototype on the weekend to get a starting point for some discussions.

**Comment by m4b** [comment]
Go for it!

**Comment by messense** [comment]
Thank you @johannst
