### ISSUE TITLE
Finding path to dll import locations

### ISSUE THREAD

**Issue by ryancinsight** [m4b/goblin#264]
Hello, 

Is there a way to use goblin to not only read a dll name but get the paths of dll files imported. I'm trying to implement a folder dependency walker that parses the dll files to create a hashmap of dll name and path to it's location as shown in this repository main.rs: https://github.com/ryancinsight/depwalker 

Any ideas or suggestions would be greatly appreciated.

**Comment by messense** [comment]
Maybe you can take inspiration from crosstool-ng's `ldd` script: https://gist.github.com/jerome-pouiller/c403786c1394f53f44a3b61214489e6f

**Comment by ryancinsight** [comment]
Thanks!
