### ISSUE TITLE
Does Goblin intend to support binary generation?

### ISSUE THREAD

**Issue by kotauskas** [m4b/goblin#266]
A format parser and a builder for the same format more often than not share a majority of code. Since Goblin aims to be the one-stop shop for decompilation and analysis, I'm wondering if extending it to support generating executables aligns with the goals for the crate. If not, what would be a good crate to assist in generating executable files?

**Comment by philipc** [comment]
[faerie](https://github.com/m4b/faerie) uses goblin, but only supports generating object files. I'm not aware of anything that generates executables (that's normally the linker's job, and there's not much need to write new linkers). This probably belongs in a new crate. You could certainly use goblin to assist with this though.

**Comment by m4b** [comment]
I think this question was answered, let me know if you have any other questions, thank you!
