### ISSUE TITLE
Missing tag for 0.4.3?

### ISSUE THREAD

**Issue by XVilka** [m4b/goblin#287]
I see there is even a changelog with some fixes for 0.4.3 (even with the date defined: `## [0.4.3] - 2021-9-18`) but no tag yet. Was it forgotten or just not ready yet?

https://github.com/m4b/goblin/commit/289baf559d81a581c59c6a9b66810b408963602b

**Comment by m4b** [comment]
Sorry I missed this, will add a tag

**Comment by m4b** [comment]
I'm only a year late, and many releases since, but I've tagged it now I believe :)
