### ISSUE TITLE
No way to obtain index_type from goblin::archive::Archive

### ISSUE THREAD

**Issue by antze-k** [m4b/goblin#289]
The docs for IndexType say "The type of symbol index can be present in an archive. Can serve as an indication of the archive format." but there's no way to get that indication since the field is private.

Maybe the field should be made pub, or there should be a method for getting its value?

**Comment by m4b** [comment]
is there a specific usecase you want here, I think the archive api works for most people, so if you're having an issue, or you want to do something, feel free to re-open and paste with some example code, or make a PR demonstrating what you'd like, thanks!
