### ISSUE TITLE
Mach-O: improve entrypoint handling

### ISSUE THREAD

**Issue by willglynn** [m4b/goblin#29]
Comparing `goblin`'s implementation and my current working memory of `dyld`, I have two observations:

1. `LC_MAIN` and `LC_UNIXTHREAD` both provide entrypoint locations, but the environments provided by each are not interchangeable. (See [`dyld.cpp`](https://github.com/opensource-apple/dyld/blob/master/src/dyld.cpp#L4955-L4968), [`dyldStartup.s`](https://github.com/opensource-apple/dyld/blob/master/src/dyldStartup.s#L172-L191).) Last time I needed to know the entrypoint of a Mach-O executable, I had to know which kind it was; `struct MachO` should probably retain this distinction.
2. All those registers in the `LC_UNIXTHREAD` thread state? You know, the arch-specific thread states which are not currently handled by `goblin`? Good news: they don't matter in the slightest. [`dyld` uses only the instruction pointer](https://github.com/opensource-apple/dyld/blob/3f928f32597888c5eac6003b9199d972d49857b5/src/ImageLoaderMachO.cpp#L1061-L1095), and the rest are entirely discarded. This makes them unusable in practice, and thus they're always zero.

**Comment by m4b** [comment]
I like to pretend that `LC_UNIXTHREAD` doesn't exist :hearnoevil:

Second point is good to know, iiuc, this is the current behavior and nothing needs to change ?

I'm not sure I understand the first point completely though? The address in either case is a vm address, iirc, and it shouldn't matter how I arrived at the value, no?

Especially since I think almost all OS X binaries are all PIC and all dynamically linked, unless you happen to have a very old version, but even then I'm not sure it's  too important ?

Would have to see an older binary, likely 10.1 to see if this is an issue

**Comment by willglynn** [comment]
The second point means `goblin` doesn't need to have a ton of different thread state structs. Given that only one register matters, all the arch-specific thread state structs can be boiled down to a single `u64`. `goblin` still needs to know how to find that value for each architecture since the offset and size vary, but the `LC_UNIXTHREAD`-encapsulating struct doesn't need to remember AVX/MMX registers on x86 separately from ARM and PPC since `dyld` ignores them anyway.

The first point is noting that `LC_MAIN` and `LC_UNIXTHREAD` specify entrypoints with two different properties. I suppose it's fine to consolidate them into a single `pub entry: u64` for consistency with other formats, since it is the entrypoint in either case, but it would be helpful to have a flag indicating which kind of entrypoint `pub entry: u64` describes. `dyld` configures the stack in different ways (alignment, args, return address) depending on which load command it's using, so if you're trying to do something with `pub entry: u64`, you probably need to know which model to use.

Note also that it's legal to specify both `LC_MAIN` and `LC_UNIXTHREAD`, and `dyld` always chooses `LC_MAIN` over `LC_UNIXTHREAD` regardless of how they're ordered in the file. `goblin` should probably do the same.

**Comment by m4b** [comment]
Ah k, we'll choose main or thread and add a new flag to the struct stating whether it was from modern or old version in case a client wants to know this. 

Thanks for the info, will implement this asap !
