### ISSUE TITLE
Support for COFF object files

### ISSUE THREAD

**Issue by koutheir** [m4b/goblin#324]
COFF object files are not supported. The function [goblin::peek()](https://docs.rs/goblin/latest/goblin/fn.peek.html) doesn't seem to support this COFF format.

This lack of support causes the [issue #36 in `bingrep`](https://github.com/m4b/bingrep/issues/36), reproducible as follows:
```bash
$ rustup target add x86_64-pc-windows-gnu
$ echo "" | rustc --target x86_64-pc-windows-gnu --emit obj - --crate-type lib
$ bingrep rust_out.o
Unknown magic: 0x38664
```

Whereas:
```bash
$ file rust_out.o
rust_out.o: Intel amd64 COFF object file, not stripped, 3 sections, symbol offset=0x8c, 10 symbols, 1st section name ".text"
```

**Comment by koutheir** [comment]
Another issue that hinders COFF support is the assumption of `Strtab::parse()` that strings stored in string tables are all encoded as UTF-8.

The following produces a simple PE/COFF object file whose string table contains a string that is encoded in `ISO-8859-1`:
```shell
$ echo 'static ONE: &str = "One."; static TWO: &str = "Two!"; static mut THREE: &str = "17"; pub extern "C" fn four() -> usize { 17 }' | \
    rustc --target x86_64-pc-windows-gnu --emit obj - --crate-type lib
```

**Comment by m4b** [comment]
i'm hoping a hero comes along and fixes this issue :) @koutheir it sounds like `peek` just needs to be made aware of coff object file magic numbers?

**Comment by koutheir** [comment]
> it sounds like `peek` just needs to be made aware of coff object file magic numbers?

That should help.
