### ISSUE TITLE
Parsing relocations in a PE file

### ISSUE THREAD

**Issue by lexika979** [m4b/goblin#392]
Hello,
I may need some help understanding how to use goblin for my use case.
I'd like to manually map a PE and execute it. Of course, i need to first fix the relocations so that the addresses match.
Unfortunately, I cannot find a way to do this with goblin. I tried something like this:
```
        let pe = PE::parse(&self.bytes)?;
        for sec in pe.sections {
            if let Ok(mut v) = sec.relocations(&self.bytes) {
                debug!("{} {:?}", String::from_utf8(sec.name.to_vec())?, v.next());
            }
        }
```
And also some other things, but cannot get it to work.
I'd appreciate any advice! :)

**Comment by philipc** [comment]
PE uses relocations in the base relocation data directory, not COFF relocations in sections. You can use [get_base_relocation_table](https://docs.rs/goblin/latest/goblin/pe/data_directories/struct.DataDirectories.html#method.get_base_relocation_table) to get the data directory, but there doesn't appear to be anything to parse it yet.

**Comment by lexika979** [comment]
Right, so maybe that should be something mentioned in the readme, especially if goblin claims to be the "one-stop shop for binary parsing, loading, and analysis"

**Comment by philipc** [comment]
No, it would be more appropriate for it to be added to goblin. PRs are accepted.
