### ISSUE TITLE
Status of 32 bit ELF

### ISSUE THREAD

**Issue by flanfly** [m4b/goblin#4]
Hey @m4b, I saw you added structure definitions for 32 bit ELF files. Is there any plan to implement `Elf::from_fd` for 32 bits, too? I only had a brief look at it, but it looks like you'd need to duplicate most of the code for the 64 ELF files.

**Comment by m4b** [comment]
Why hello @flanfly ! Yes indeed, that was the plan (in fact, the grand plan is to add binary targets for the three major ones, ELF, mach, and PE, finalize the api, and then release 1.0 - I'm in the process of adding mach, but it's tedious, complicated, and somewhat boring right now, so it'll take me some time :P).

As for elf32, yes I'm adding the structs right now after factoring out the modules to share as much as possible (i.e., consts, string transformers, etc.), but there will be some duplication, i.e., the `from_fd` will essentially be copy-pasta modulo the endian-aware size reads.  I suppose we could write a macro for this, but who cares?

Mostly I was concerned about the module use from an API perspective; I wanted:

1. the all binary targets to be compile time cfg-urable
2. easy type punning; i.e., stuff like `use goblin::elf32 as elf;` the `automagic.rs` example demonstrates this
3. distinguishability as well, usually for binary analysis tools, which want to know if it's 32-bit or 64-bit usually, i.e. just `use goblin::elf32;`
4. a new `pure` cfg flag; this could in principle be a `#[cfg(not(feature = "pure"))]` module scoping the various struct impls and their printers, and would include the std includes, etc.  This would allow compiling the crate for use in kernel dev, etc.  In fact I've already compiled redox with a version of goblin with this kind of flag, but haven't gotten around to telling them/making it ready.

But if you feel like filling in the endian/non-endian readers for the 32-bit ELF that would be great.  After that I'm pretty sure the major parts of the ELF target are done, minus looking into getting the gnu hashtable and strtab working (which I think won't be a major issue, might be just `pub use gnu_hash::*;` etc., just need to check the integer sizes for the different platforms), as well as other potential wishlists (if you have any, do let me know).

Oh, and I'd like to add tons of tests; I added a travis CI now, so should be nicer to see immediate changes, regressions, etc.

But that's unrelated to this issue ;)

**Comment by flanfly** [comment]
Cool, great to hear you're still working on it. The fact that goblin treats 32 and 64 bit ELF files as completely unrelated types complicates things a bit for me, but using a macro to duplicate the code that translates the `Elf` structure into my internal data structures works perfectly. While having a traits for all the structures would make it more idiomatic, this would involve writing hundreds of getter methods so who cares ;)

I will look into the endianess aware code when you're done with copy & pasting.
