### ISSUE TITLE
Perform Release

### ISSUE THREAD

**Issue by Javagedes** [m4b/goblin#423]
Hi @m4b, would you be able to perform a release so that commit https://github.com/m4b/goblin/commit/617775898fdfd0b843b2e937c80e455cf6f2a637 is available via traditional crates.io rather than a rev? Please let me know if there is anything I can do to assist. Thank you!

**Comment by m4b** [comment]
done, released in 0.9.0, thanks for pinging me! there should be 3 breaking changes included, all PE related, have a good evening!
