### ISSUE TITLE
`std` is required when `std` feature is not used

### ISSUE THREAD

**Issue by jackpot51** [m4b/goblin#50]
Due to the `log` crate, `std` is required. To fix this, remove the `use_std` feature from `log`.

**Comment by m4b** [comment]
:/

sorry this was a stupid oversight iiuc; i believe above commit fixes

@jackpot51 do you want me to publish new crate ?

**Comment by m4b** [comment]
nvm it does not

**Comment by m4b** [comment]
ok it should be fixed in b326d51
