### ISSUE TITLE
Interface to `dl_iterate_phdr`?

### ISSUE THREAD

**Issue by vext01** [m4b/goblin#70]
I've recently embedded C into a Rust project that needed the `dl_iterate_phdr()` interface.

From the OpenBSD manual:
```
SYNOPSIS
     #include <link.h>

     int
     dl_iterate_phdr(int (*callback)(struct dl_phdr_info *, size_t, void*),
         void *data);

DESCRIPTION
     The dl_iterate_phdr() function iterates over all shared objects loaded
     into a process's address space, calling callback for each shared object,
     passing it information about the object's program headers and the data
     argument.
```

The interface is somewhat portable, but there are slightly different semantics across platforms.

I would have written my interfacing code in Rust, but decided against it due to the need to define (and keep in sync) the required ELF structs.

Since goblin is fundamentally concerned with these structures, I wonder if goblin would be a good place to implement a rust interface to `dl_iterate_phdr()`?

Thanks

**Comment by fitzgen** [comment]
Fwiw, I wrote https://github.com/fitzgen/findshlibs a while back, which exposes the same API for mach-o files.


It is unfortunate that dl_iterate_phdr just gives phdr and not a edhrs too...

**Comment by fitzgen** [comment]
(same API for iterating loaded libraries across both osx and other nixes, that is. It is built on top of dl_iterate_phdr on non osx, if that wasn't clear)

**Comment by m4b** [comment]
@vext01 Thanks for the issue!

Could you clarify what some of your usecases are?  Specifically, one thing I'm wondering is if you want goblin exposing an unmangled `dl_iterate_phdr` symbol and to use it as a stand-in/at the ABI level for a library exposing that functionality?

If so, I'm pretty sure you could fairly easily write the implementation using goblin at a fairly high level, and then compile it as a static/dynamic lib and use it as a stand-in for that symbol. I won't merge any PR adding an unmangled symbol into goblin as this has already caused problems in the past, specifically can cause linking issues with projects with more than one goblin version.

Alternatively, as @fitzgen points out, they seem to have a crate that exposes a nicer/more rusty api for iterating shared libraries, whose only deficiency, of course, is not using goblin for the backing structs ;P

Peeking at the implementation, it appears it won't load binaries from foreign container formats/endianness, but I'm 99% sure that `dl_iterate_phdr` doesn't/isn't supposed to do this either.

If you wanted to load binaries and iterate them for foreign architectures, goblin will allow you to do this (as well as native loading).

If you want to do the latter with goblin, I can point you to https://github.com//m4b/dryad/blob/b26dc12c96919e3fe2fd3515c41832b0be191300/src/loader.rs#L73 which could serve as inspiration for unsafely loading a file from memory, mmaps the segments, and prepares other niceties, similar to how a dynamic linker prepares the shared object.

So, depends on what you want to do, and you've probably got lots of options!

1. Use findshlibs
2. Write simple goblin backed wrapper yourself
3. Write cross-platform iterator with goblin
4. Write native shared object loader

If you end up using goblin for whatever reason and have any questions, don't hesitate to let me know.

If you also end up using the core or std feature flag in goblin, e.g. something like:

```
goblin = { version = "0.11", features = ["elf32", "elf64"] } // or maybe "std", if you need std io functionality
```

let me know how it goes; there are a few convenience functions/apis I've meant to port to the core only API, but haven't had time.

Take care, and good luck!

**Comment by m4b** [comment]
I believe this is out of scope/and or answered by my post above, please re-open if i've misunderstood :)

**Comment by vext01** [comment]
In the end I wrote my own little library for interfacing with `dl_iterate_phdr`:
https://github.com/softdevteam/phdrs

Thanks.
