### ISSUE TITLE
rlib support

### ISSUE THREAD

**Issue by RazrFalcon** [m4b/goblin#72]
What about `rlib` support used by Rust itself. It's mostly an `ar` afiak and the `ar` crate supports Linux variant of it (no support for macOS version for some reason).

**Comment by m4b** [comment]
Hi @razrfalcon !

What support in particular did you have in mind ?

Goblin can already parse rlibs and print the symbols and who contains them. 

For an example try running [bingrep](https://GitHub.com/m4b/bingrep) on an rlib (I even added an extractor flag, `—extract`, for pulling out the bytes of a member in an rlib)

Let me know if you have any issues or you had something else in mind !

**Comment by RazrFalcon** [comment]
I doesn't tried `goblin` directly. I used `object` crate. Maybe it's not complete.

Currently, I interested only in symbols list.

**Comment by m4b** [comment]
Ah yea, object doesn’t support archives at the moment. Not sure if it’s planned. /cc @philipc would know better if that’s in scope for that crate. 

On goblin side, Goblin provides a convenience method for this: https://github.com/m4b/goblin/blob/master/src/archive/mod.rs#L441

If you want to call this yourself, just call `goblin::Object::parse`, match on the Artifact enum variant, and then call the above method on it.

Let me know if you have any problems!

**Comment by philipc** [comment]
I'm happy to merge a PR to add rlib support in the `object` crate if it makes sense. I don't know how well the `Object` trait fits with rlibs, so far I've been more focused on executables.

It may be better to instead iterate over the archive members and use `object` for each member. You'll need this for archives without an index (do rlibs normally have an index?).

**Comment by RazrFalcon** [comment]
Everything works fine. Thanks.

**Comment by m4b** [comment]
@philipc Yea rlibs always have an index but they don’t necessarily have to have a symbol index iirc. I’d check goblin source or the wiki page on archiver or the man page on a nix system to be sure. 

The other thing is they don’t have to contain executables can contain anything technically (just a blob of bytes), but for most cases I guess you could assume they’re a homogenous container of a list of object files, and ignore anything else that doesn’t parse?
