### ISSUE TITLE
Parsing PE with empty export data directory

### ISSUE THREAD

**Issue by tathanhdinh** [m4b/goblin#76]
Some well-formed PE may have its export data directory with an empty table of `NumberOfFunctions` (as well as `NumberOfNames`,  `AddressOfFunctions`, etc.), for example the `Export Data Directory` of `apisetschema.dll` (a dll for [API redirection](https://blog.quarkslab.com/runtime-dll-name-resolution-apisetschema-part-i.html) from Windows 7) on my machine `Windows7.SP1`:

![apisetschema](https://user-images.githubusercontent.com/79418/35662192-18e7d004-0717-11e8-8fff-368edf4e963f.PNG)

But the PE parser of goblin will refuse such a PE, that is because of some checks, for example when parsing the [`AddressOfNames`](https://github.com/m4b/goblin/blob/master/src/pe/export.rs#L76):

`let name_pointer_table_offset = &mut utils::find_offset_or(export_directory_table.name_pointer_rva as usize, sections, &format!("Cannot map export_directory_table.name_pointer_rva ({:#x}) into offset", export_directory_table.name_pointer_rva))?;`

because `export_directory_table.name_pointer_rva` will be zero then the including function `parse` returns immediately with an `Err(_)`.

The same with `AddressOfNameOrdinals` and `AddressOfFunctions` tables, a quick-and-dirty fix might be checking the value of `export_directory_table.number_of_name_pointers` and of `export_directory_table.address_table_entries`  with `0` before parsing offsets of these tables:

```
let mut export_name_pointer_table: ExportNamePointerTable = Vec::with_capacity(number_of_name_pointers);
let mut export_ordinal_table: ExportOrdinalTable = Vec::with_capacity(number_of_name_pointers);

if number_of_name_pointers > 0 {
    let name_pointer_table_offset = &mut utils::find_offset_or(export_directory_table.name_pointer_rva as usize, sections, &format!("Cannot map export_directory_table.name_pointer_rva ({:#x}) into offset", export_directory_table.name_pointer_rva))?;
    for _ in 0..number_of_name_pointers {
        export_name_pointer_table.push(bytes.gread_with(name_pointer_table_offset, scroll::LE)?);
    }

    let export_ordinal_table_offset = &mut utils::find_offset_or(export_directory_table.ordinal_table_rva as usize, sections, &format!("Cannot map export_directory_table.ordinal_table_rva ({:#x}) into offset", export_directory_table.ordinal_table_rva))?;

    for _ in 0..number_of_name_pointers {
        export_ordinal_table.push(bytes.gread_with(export_ordinal_table_offset, scroll::LE)?);
    }
}

let mut export_address_table: ExportAddressTable = Vec::with_capacity(address_table_entries);
if address_table_entries > 0 {
    let export_address_table_offset = utils::find_offset_or(export_directory_table.export_address_table_rva as usize, sections, &format!("Cannot map export_directory_table.export_address_table_rva ({:#x}) into offset", export_directory_table.export_address_table_rva))?;
    let export_end = export_rva + size;
    let offset = &mut export_address_table_offset.clone();
    
    for _ in 0..address_table_entries {
        let rva: u32 = bytes.gread_with(offset, scroll::LE)?;
        if utils::is_in_range(rva as usize, export_rva, export_end) {
            export_address_table.push(ExportAddressTableEntry::ForwarderRVA(rva));
        } else {
            export_address_table.push(ExportAddressTableEntry::ExportRVA(rva));
        }
    }
}
```

**Comment by m4b** [comment]
Hey @tathanhdinh thanks for opening the issue!

Yea, confirmed; actually this is a problem for a whole lot of other standard windows binaries.

If you think your patch will work, and can add a test case, I'll definitely merge it!

@willglynn what do you think?

I've noticed the goblin parser also reports stuff like `storage.dll` has a magic of 0, which seems weird, as hexdumping the binary seems to appear like a typical PE binary, but that's probably another issue

**Comment by willglynn** [comment]
@m4b I know enough about PE to be dangerous, but not enough to have an opinion here.

**Comment by tathanhdinh** [comment]
@m4b thanks for your feedback. 
Sure, I will prepare a test case.
