### ISSUE TITLE
Universal executable

### ISSUE THREAD

**Issue by kpp** [m4b/goblin#81]
Hello.

Is it possible to generate such a file that can be correctly parsed both with PE and ELF readers? Even if the executable would do nothing like `int main() {}`.

**Comment by willglynn** [comment]
Maybe with some executable formats, but not any combination of PE, ELF, or Mach-O. They all require the file to start with different magic numbers.

**Comment by kpp** [comment]
> They all require the file to start with different magic numbers.

Ah. Thank you for your rapid response.
