### ISSUE TITLE
Allow zero-copy reading of native endian binaries

### ISSUE THREAD

**Issue by luser** [m4b/goblin#9]
For the simple case, where you're reading a binary of native endianness, it would be nice if the API allowed doing this without copying memory. @nrc has [a very simple elf parser](https://github.com/nrc/xmas-elf/) that uses his [zero](https://github.com/nrc/zero) crate to acheve this.  The API winds up looking like:

``` rust
pub fn parse_header<'a>(input: &'a [u8]) -> Header<'a> 
```

Your current implementation is very close, but it does clone the resulting `Header`:
https://github.com/m4b/goblin/blob/7d21ea43fe093c1a75747b68da227dcf0d4664b4/src/elf/mod.rs#L110

It would be even nicer if the API returned an error for non-native endianness so consumers could fall back to `from_fd_endian`.

**Comment by m4b** [comment]
@luser why hello, thanks for the issue!

So, first part: I agree it would be nice to not copy the header, but correct me if I'm wrong (and this seems to be the implementation taken in `xmas-elf`) the only way to "zero-copy" is to add a lifetime to the Header, which is then tied to the input bytes.

This then essentially embeds a reference whose lifetime is tied to the Header lifetime.  This of course is quite reasonable, but most of the use cases for this crate are for `repr(C)` use cases, i.e., dynamic loading, kernel development, etc.  In principle there's nothing stopping the other approach from being taken, but it makes it harder to [cast a blob of bytes as a header](https://github.com/m4b/dryad/blob/master/src/linker.rs#L200), and other similar niceties.

So in the line you've given, I suppose we could return a reference to the header which is tied to the lifetime of the bytes.  I think I do something like this in `strtab.rs` (but don't look at that, it's kind of unsafe :P)

The problem with that though is it's just so much nicer to work with owned structs, and not having to worry about lifetimes.  It's simpler, and arguably, makes the API much more ergonomic.

Lastly, not copying when you don't have to is great, but I wonder if this might be a premature optimization; we're only copying 48 bytes; even [if you're parsing and copying thousands of ELF _binaries_](https://github.com/m4b/rdr#symbol-map), this typically won't be the performance bottleneck.

Nevertheless, if you have some ideas on how to make this possible, while keeping in mind the above (i.e., `repr(C)` isn't going anywhere), I'm definitely all ears!

For your second point, that might be doable, but I'm not quite sure what you mean exactly though.  So the one feature set eschews endian parsing (this will be for dynamic linkers and kernels which always assume the endianness is equal to the platform); the other version, which is endian-aware parsing, which would be binary analysis tools, automatically parses the header/binary depending on whether the binary says it's little endian or big endian, so we don't really need to fallback to a different strategy.  Or perhaps I've misunderstood your suggestion?

Hope that makes sense and thanks for the issue :)

**Comment by m4b** [comment]
So. I have an idea how to make parsing faster a la combination of references, less copying, and what not. It'll have a number of benefits hopefully.

But it will involve me writing 2 separate crates :/ one of them is half done, other is not really started.

However, I think it will be worth it and will solve a number of technical problems I keep encountering when using goblin in day to day activities.

Also, it can be _very_ slow right now, and I think this will also be fixed.

Anyway, that's the status on slightly greater than zero-copy reading of binaries.  Stayed tuned?

**Comment by luser** [comment]
Yes. :) Sorry, have a potential use for this but it's not something I'm actively working on daily so I lose track of it sometimes.

**Comment by m4b** [comment]
No worries! Just letting you know about a general status update on this issue :)

**Comment by m4b** [comment]
I think @le-jzr had some ideas about this, and did some great work making the unsafe zero-copy transmutes working well, but i'm not sure exactly how it would look.

For a loader, which I think is the primary usecase, this is about as efficient as it gets: https://github.com/m4b/dryad/blob/b26dc12c96919e3fe2fd3515c41832b0be191300/src/loader.rs#L73

but I don't think it would integrate well with the current parser (nor does it _necessarily_ need to)

just some ideas

**Comment by le-jzr** [comment]
Funnily enough, the above-mentioned `zero` crate does almost exactly what `plain` does, except the name and description is so obscure it didn't come up in any searches when I was looking for crates like that.  *shrug*

**Comment by m4b** [comment]
Ok, so closing this, since I think the zero-copy/endianness story has been sufficiently set in stone for goblin at least, and is discussed elsewhere, so this (the oldest issue in goblin!) can be closed :) please reopen if i've misunderstood

**Comment by luser** [comment]
Yeah, I think what you're doing is fine.
