### ISSUE TITLE
Nlist's str_x field has host-sensitive size

### ISSUE THREAD

**Issue by sunfishcode** [m4b/goblin#92]
In `goblin::mach::symbols::Nlist`, the `str_x` field has type `usize`. Since this represents an external format, it should have a host-independent type.

For comparison, LLVM's corresponding data structure uses `u32` for this field: https://github.com/llvm-mirror/llvm/blob/4604874612fa292ab4c49f96aedefdf8be1ff27e/include/llvm/BinaryFormat/MachO.h#L964

**Comment by philipc** [comment]
`Nlist` is not an external format. `Nlist32` and `Nlist64` represent the external format. While both `Nlist32` and `Nlist64` use `u32` for `str_x`, I think `usize` was chosen for `Nlist` because within goblin `str_x` is used as a slice offset, and `usize` is an appropriate type for that.

**Comment by sunfishcode** [comment]
Ah, I see. Thanks!

**Comment by willglynn** [comment]
@philipc I was just writing something similar :-)

@sunfishcode Note also: LLVM's `nlist_base` omits `value`, whereas `goblin::mach::symbols::Nlist` provides it as a `u64`. `Nlist` is for convenience, not 1:1 correspondence with bits on disk. making Representing `value` as a `u64` is convenient; representing `n_strx` and `n_sect` as `usize` is similarly convenient.
