### ISSUE TITLE
Could not find `btree_map` in `alloc`

### ISSUE THREAD

**Issue by gz** [m4b/goblin#94]
Hmm ok filing an issue since I don't quite understand the interaction here...
If I compile goblin 8bbbcf5 directly with `cargo +nightly build --no-default-features --features alloc` it works fine.

If I try to compile the object crate with the goblin dependency declared as follows:
```
[dependencies.goblin]
git = "https://github.com/m4b/goblin"
default-features = false
features = ["alloc", "endian_fd", "elf32", "elf64", "mach32", "mach64", "pe32", "pe64", "archive"]
```
Using `cargo +nightly build --no-default-features` or `cargo +nightly build -v --no-default-features --features goblin/alloc`, I get:

```
   Compiling goblin v0.0.16 (https://github.com/m4b/goblin#8bbbcf5d)
error[E0432]: unresolved import `alloc::btree_map`==========>          ] 10/12: goblin
  --> /Users/gz/.cargo/git/checkouts/goblin-d0c041c0a85ca4ca/8bbbcf5/src/archive/mod.rs:15:12
   |
15 | use alloc::btree_map::BTreeMap;
   |            ^^^^^^^^^ Could not find `btree_map` in `alloc`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `goblin`.

To learn more, run the command again with --verbose.
```

The following diff https://github.com/gz/goblin/commit/a6369aced1a09e8a2c2f75e347491e2c75fd97cc fixes the problem.

**Comment by philipc** [comment]
You need to enable more features when building goblin to trigger the error, since there's individual features for the various file formats too, ie you need the `archive` feature in particular for this error. See the `nightly_api` target in the top level Makefile for a convenient way to test all the feature combinations.

**Comment by m4b** [comment]
@gz 0.0.17 should be available for your no-std pleasure; i'm not sure if object has to update its goblin dep explicitly (probably). Please raise another issue if you encounter any other errors! Thanks for your help here :)
